[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
src_paths = ["."]

[tool.mypy]
python_version = '3.8'
files = ['*.py']
exclude = ["venv", "docs"]

show_error_codes = true
namespace_packages = false
check_untyped_defs = true

warn_redundant_casts = true
warn_unused_ignores = true

# Silint "type import errors" as our 3rd-party libs does not have types
# Check: https://mypy.readthedocs.io/en/latest/config_file.html#import-discovery
follow_imports = 'silent'

[[tool.mypy.overrides]]
module = []
ignore_missing_imports=true

[tool.ruff]
exclude = ["build", "dist", "env", ".venv"]
lint.select = ["E", "F", "W"]

[tool.flake8]
max-line-length = 88

[tool.pytest.ini_options]
addopts = '-s -vvv --cache-clear'
asyncio_mode = 'auto'
cache_dir = '/tmp'
python_files = 'tests.py test_*.py'
python_functions = 'test_* *_test'
markers = [
    "smoke: quick tests to check basic functionality",
    "sanity: detailed tests to ensure major functions work correctly",
    "regression: tests to ensure that new changes do not break existing functionality"
]

