name: Publish Python distribution to PyPI

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install pypa/build nad pypa/twine
        run: >-
          python3 -m pip install build twine --user

      - name: Build a binary wheel
        run: python3 -m build

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: 🚀📦 Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

        run: python -m twine upload dist/*
