name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.13"
          - "3.9"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install tox
      - name: Run quality checks
        run: tox -e quality

  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.13"
          - "3.9"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install tox
      - name: Run type checks
        run: tox -e types

  precommit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit checks
        run: pre-commit run --all-files
